linux (Allwinner): rebase and drop upstreamed patches in 6.9 - 6.14
- https://github.com/torvalds/linux/commit/3ce7384048fa1793db0eae013fa377d89256b76f
- The following changes were introduced in 6.11-rc1 and 6.11-rc7
  only pass 3 variables to
  - of: remove internal arguments from of_property_for_each_u32()
  - https://github.com/torvalds/linux/commit/9722c3b66e21ff08aec570d02a97d331087fd70f
  6.11-rc7 has refactored drm https://github.com/torvalds/linux/commit/9da7ec9b19d8c1ad4f44e459fa5f93ad7a117dcd
  resulting in the following compile error.
  build.LibreELEC-H6.aarch64-13.0-devel/toolchain/bin/aarch64-libreelec-linux-gnu-ld: drivers/gpu/drm/sun4i/sun8i_dw_hdmi.o: in function `sun8i_dw_hdmi_bind':
  build.LibreELEC-H6.aarch64-13.0-devel/build/linux-6.11-rc7/drivers/gpu/drm/sun4i/sun8i_dw_hdmi.c:394:(.text+0x73c): undefined reference to `drm_bridge_connector_init'
- https://github.com/torvalds/linux/commit/db300ab0e9d38b1e1b0b561333b66a5beacb9994
- allwinner: OrangePi PC also needs SW CEC hack
  CEC stopped working after updating from LE10 to LE11 as the former enabled
  the SW CEC hack for all H3 boards and the latter only for specific boards.
  Add OrangePi PC to that list of specific boards.
- Use old OrangePi 3 net patches
- Switch PMIC connection to I2C

Co-authored-by: Jernej Skrabec <jernej.skrabec@gmail.com>